env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - standard-with-typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - ./tsconfig.json
    - ./functions/tsconfig.json
    - ./tsconfig.node.json
plugins:
  - react
rules:
  {
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/triple-slash-reference': 'off'
  }
settings:
  react:
    version: detect
